In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from pathlib import Path
sns.set_style("whitegrid")

In [34]:
demographics=pd.read_csv('./demographics/demographics_cleaned.csv')
demographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 43 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        3220 non-null   int64
 1   GEO_ID            3220 non-null   object
 2   NAME              3220 non-null   object
 3   total_pop         3220 non-null   int64
 4   pop_0_5           3220 non-null   int64
 5   pop_5_10          3220 non-null   int64
 6   pop_10_15         3220 non-null   int64
 7   pop_15_20         3220 non-null   int64
 8   pop_20_25         3220 non-null   int64
 9   pop_25_30         3220 non-null   int64
 10  pop_30_35         3220 non-null   int64
 11  pop_35_40         3220 non-null   int64
 12  pop_40_45         3220 non-null   int64
 13  pop_45_50         3220 non-null   int64
 14  pop_50_55         3220 non-null   int64
 15  pop_55_60         3220 non-null   int64
 16  pop_60_65         3220 non-null   int64
 17  pop_65_70         3220 non-null   int64
 18  pop_70_75         3220 non-null   int64
 19  pop_75_80         3220 non-null   int64
 20  pop_80_85         3220 non-null   int64
 21  pop_85_90         3220 non-null   int64
 22  pop_18_24         3220 non-null   int64
 23  total_male_pop    3220 non-null   int64
 24  pop_male_0_5      3220 non-null   int64
 25  pop_male_5_10     3220 non-null   int64
 26  pop_male_10_15    3220 non-null   int64
 27  pop_male_15_20    3220 non-null   int64
 28  pop_male_20_25    3220 non-null   int64
 29  pop_male_25_30    3220 non-null   int64
 30  pop_male_30_35    3220 non-null   int64
 31  pop_male_35_40    3220 non-null   int64
 32  pop_male_40_45    3220 non-null   int64
 33  pop_male_45_50    3220 non-null   int64
 34  pop_male_50_55    3220 non-null   int64
 35  pop_male_55_60    3220 non-null   int64
 36  pop_male_60_65    3220 non-null   int64
 37  pop_male_65_70    3220 non-null   int64
 38  pop_male_70_75    3220 non-null   int64
 39  pop_male_75_80    3220 non-null   int64
 40  pop_male_80_85    3220 non-null   int64
 41  pop_male_85_90    3220 non-null   int64
 42  pop_male_105_110  3220 non-null   int64
dtypes: int64(41), object(2)
memory usage: 1.1+ MB

In [35]:
#better_demographics=demographics[['GEO_ID','NAME']]

In [36]:
demographics['pop_18_30']=demographics['pop_18_24']+demographics['pop_25_30']
demographics['pop_18_30_pc']=100*demographics['pop_18_30']/demographics['total_pop']
demographics['pop_60_up']=demographics['pop_60_65']+demographics['pop_65_70']+demographics['pop_70_75']+demographics['pop_75_80']+demographics['pop_80_85']+demographics['pop_85_90']
demographics['pop_60_up_pc']=100*demographics['pop_60_up']/demographics['total_pop']

demographics['pop_male_pc']=100*demographics['total_male_pop']/demographics['total_pop']
final_tally=demographics[['GEO_ID','NAME','total_pop','pop_18_30_pc','pop_60_up_pc','pop_male_pc']]

In [37]:
final_tally.set_index('GEO_ID',inplace=True)

In [38]:
final_tally.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, 0500000US01001 to 0500000US72153
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NAME          3220 non-null   object
 1   total_pop     3220 non-null   int64
 2   pop_18_30_pc  3220 non-null   float64
 3   pop_60_up_pc  3220 non-null   float64
 4   pop_male_pc   3220 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 150.9+ KB

In [39]:
dp_2016=pd.read_csv('./demographics/dp_2016_cleaned.csv')
dp_2019=pd.read_csv('./demographics/dp_2019_cleaned.csv')
dp_2016.drop(axis=1,labels=['Unnamed: 0'],inplace=True)
dp_2019.drop(axis=1,labels=['Unnamed: 0'],inplace=True)
dp_2016.set_index('GEO_ID',inplace=True)
dp_2019.set_index('GEO_ID',inplace=True)

In [40]:
dp_2019.loc[:,'tot_pop']

GEO_ID
0500000US01001     55380
0500000US01003    212830
0500000US01005     25361
0500000US01007     22493
0500000US01009     57681
                   ...
0500000US72145     52192
0500000US72147      8642
0500000US72149     22403
0500000US72151     33499
0500000US72153     35428
Name: tot_pop, Length: 3220, dtype: int64

In [41]:
delta_dp=dp_2016[['NAME']]
for x in dp_2016.columns:
    if x != 'NAME':
        dp_2016[x+'_pc']=100*dp_2016[x]/dp_2016['tot_pop']
        dp_2019[x+'_pc']=100*dp_2019[x]/dp_2019['tot_pop']
        delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
delta_dp.drop(axis=1,labels=['tot_pop_delta'],inplace=True)

/tmp/ipykernel_11156/176667491.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
/tmp/ipykernel_11156/176667491.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
/tmp/ipykernel_11156/176667491.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
/tmp/ipykernel_11156/176667491.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
/tmp/ipykernel_11156/176667491.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
/tmp/ipykernel_11156/176667491.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.loc[:,x+'_delta']=dp_2019[(x+'_pc')]-dp_2016[(x+'_pc')]
/tmp/ipykernel_11156/176667491.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delta_dp.drop(axis=1,labels=['tot_pop_delta'],inplace=True)

In [42]:
cols=['afr_amer','amer_ind','asian','latino','white']
final_tally.loc[:,[x+'_pc' for x in cols]]=dp_2019.loc[:,[ x+'_pc' for x in cols]]
final_tally.loc[:,[x+'_delta' for x in cols]]=delta_dp.loc[:,[x+'_delta' for x in cols]]

In [43]:
final_tally.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3220 entries, 0500000US01001 to 0500000US72153
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NAME            3220 non-null   object
 1   total_pop       3220 non-null   int64
 2   pop_18_30_pc    3220 non-null   float64
 3   pop_60_up_pc    3220 non-null   float64
 4   pop_male_pc     3220 non-null   float64
 5   afr_amer_pc     3220 non-null   float64
 6   amer_ind_pc     3220 non-null   float64
 7   asian_pc        3220 non-null   float64
 8   latino_pc       3220 non-null   float64
 9   white_pc        3220 non-null   float64
 10  afr_amer_delta  3220 non-null   float64
 11  amer_ind_delta  3220 non-null   float64
 12  asian_delta     3220 non-null   float64
 13  latino_delta    3220 non-null   float64
 14  white_delta     3220 non-null   float64
dtypes: float64(13), int64(1), object(1)
memory usage: 402.5+ KB

In [44]:
poverty_2019=pd.read_csv('./poverty/poverty_2019_cleaned.csv',engine='python')
poverty_2016=pd.read_csv('./poverty/poverty_2016_cleaned.csv',engine='python')
poverty_2016.set_index('GEO_ID',inplace=True)
poverty_2019.set_index('GEO_ID',inplace=True)
poverty_2016.drop(axis=1,labels=['Unnamed: 0'],inplace=True)
poverty_2019.drop(axis=1,labels=['Unnamed: 0'],inplace=True)

In [45]:
poverty_2016['pov_pc']=100*poverty_2016['tot_poverty']/final_tally['total_pop']
poverty_2019['pov_pc']=100*poverty_2019['tot_poverty']/final_tally['total_pop']
poverty_2016['pov_150_pc']=100*poverty_2016['pov_150']/final_tally['total_pop']
poverty_2019['pov_150_pc']=100*poverty_2019['pov_150']/final_tally['total_pop']

In [46]:
final_tally['pov_pc']=poverty_2019['pov_pc']
final_tally['pov_pc_delta']=poverty_2019['pov_pc']-poverty_2016['pov_pc']

/tmp/ipykernel_11156/69067233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['pov_pc']=poverty_2019['pov_pc']
/tmp/ipykernel_11156/69067233.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['pov_pc_delta']=poverty_2019['pov_pc']-poverty_2016['pov_pc']

In [47]:
final_tally[:5]

,NAME,total_pop,pop_18_30_pc,pop_60_up_pc,pop_male_pc,afr_amer_pc,amer_ind_pc,asian_pc,latino_pc,white_pc,afr_amer_delta,amer_ind_delta,asian_delta,latino_delta,white_delta,pov_pc,pov_pc_delta
GEO_ID,,,,,,,,,,,,,,,,,
0500000US01001,"Autauga County, Alabama",55380,15.185988,19.902492,48.634886,19.028530,0.252799,1.034670,2.825930,76.791260,0.506849,-0.157744,0.228115,0.253676,-0.069355,15.059588,2.966775
0500000US01003,"Baldwin County, Alabama",212830,12.994879,27.178029,48.628483,9.264671,0.772917,0.925152,4.562797,86.205422,-0.055162,0.093753,0.254508,0.196098,-0.226837,10.197810,-1.807546
0500000US01005,"Barbour County, Alabama",25361,15.444975,25.022673,52.919838,47.576988,0.323331,0.528370,4.357084,46.800205,-0.352673,0.150490,0.043663,0.047322,0.095463,27.108553,2.523560
0500000US01007,"Bibb County, Alabama",22493,14.591206,22.442538,54.016805,22.291380,0.133375,0.120037,2.574134,76.788334,1.079258,-0.225477,0.058014,0.350140,-0.165414,16.627395,1.556040
0500000US01009,"Blount County, Alabama",57681,13.876320,24.505470,49.401016,1.608849,0.079749,0.367539,9.261282,95.459510,0.040500,-0.268580,0.208104,0.533984,0.018986,13.416896,-2.950712

In [48]:
income_2019=pd.read_csv('./income/income_2019_cleaned.csv',engine='python')
income_2016=pd.read_csv('./income/income_2016_cleaned.csv',engine='python')
income_2016.set_index('GEO_ID',inplace=True)
income_2019.set_index('GEO_ID',inplace=True)
income_2016.drop(axis=1,labels=['Unnamed: 0'],inplace=True)
income_2019.drop(axis=1,labels=['Unnamed: 0'],inplace=True)

In [49]:
urban_rural=pd.read_csv('./urban_rural/urban_rural.csv')
urban_rural=urban_rural.loc[1:]
urban_rural.set_index('GEO_ID',inplace=True)
urban_rural['P2_001N']=urban_rural['P2_001N'].apply(int)
urban_rural['P2_002N']=urban_rural['P2_002N'].apply(int)
urban_rural['P2_003N']=urban_rural['P2_003N'].apply(int)

#urban_rural['urban']= 1 if urban_rural['P2_002N']
final_tally['urban']=100*urban_rural['P2_002N']/urban_rural['P2_001N']
final_tally['rural']=100*urban_rural['P2_003N']/urban_rural['P2_001N']

/tmp/ipykernel_11156/618507180.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['urban']=100*urban_rural['P2_002N']/urban_rural['P2_001N']
/tmp/ipykernel_11156/618507180.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['rural']=100*urban_rural['P2_003N']/urban_rural['P2_001N']

In [50]:
final_tally['unemp_rate']=income_2019['unemp_rate']
final_tally['unemp_delta']=income_2019['unemp_rate']-income_2016['unemp_rate']
final_tally['mean_hhi']=income_2019['mean_hh_inc']
final_tally['med_hhi']=income_2019['med_hh_inc']

/tmp/ipykernel_11156/3753765977.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['unemp_rate']=income_2019['unemp_rate']
/tmp/ipykernel_11156/3753765977.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['unemp_delta']=income_2019['unemp_rate']-income_2016['unemp_rate']
/tmp/ipykernel_11156/3753765977.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['mean_hhi']=income_2019['mean_hh_inc']
/tmp/ipykernel_11156/3753765977.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['med_hhi']=income_2019['med_hh_inc']

In [51]:
final_tally

,NAME,total_pop,pop_18_30_pc,pop_60_up_pc,pop_male_pc,afr_amer_pc,amer_ind_pc,asian_pc,latino_pc,white_pc,...,latino_delta,white_delta,pov_pc,pov_pc_delta,urban,rural,unemp_rate,unemp_delta,mean_hhi,med_hhi
GEO_ID,,,,,,,,,,,,,,,,,,,,,
0500000US01001,"Autauga County, Alabama",55380,15.185988,19.902492,48.634886,19.028530,0.252799,1.034670,2.825930,76.791260,...,0.253676,-0.069355,15.059588,2.966775,59.323187,40.676813,3.7,-1.9,75326.0,58731.0
0500000US01003,"Baldwin County, Alabama",212830,12.994879,27.178029,48.628483,9.264671,0.772917,0.925152,4.562797,86.205422,...,0.196098,-0.226837,10.197810,-1.807546,62.413545,37.586455,4.3,-2.0,80986.0,58320.0
0500000US01005,"Barbour County, Alabama",25361,15.444975,25.022673,52.919838,47.576988,0.323331,0.528370,4.357084,46.800205,...,0.047322,0.095463,27.108553,2.523560,34.080006,65.919994,9.2,-3.6,47068.0,32525.0
0500000US01007,"Bibb County, Alabama",22493,14.591206,22.442538,54.016805,22.291380,0.133375,0.120037,2.574134,76.788334,...,0.350140,-0.165414,16.627395,1.556040,0.000000,100.000000,7.3,0.2,60182.0,47542.0
0500000US01009,"Blount County, Alabama",57681,13.876320,24.505470,49.401016,1.608849,0.079749,0.367539,9.261282,95.459510,...,0.533984,0.018986,13.416896,-2.950712,9.510603,90.489397,3.4,-2.6,65639.0,49358.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0500000US72145,"Vega Baja Municipio, Puerto Rico",52192,16.117413,25.823881,47.829169,4.960530,0.122624,0.017244,96.740880,83.206239,...,0.186625,-6.626576,44.999234,-3.893317,93.825119,6.174881,17.4,0.1,28805.0,19617.0
0500000US72147,"Vieques Municipio, Puerto Rico",8642,13.607961,28.176348,49.490859,7.532978,0.092571,0.162000,94.931729,54.732701,...,-1.431305,6.678312,45.672298,8.412405,79.161110,20.838890,7.5,-4.8,22742.0,14936.0
0500000US72149,"Villalba Municipio, Puerto Rico",22403,17.457483,22.764808,48.457796,3.450431,0.000000,0.000000,99.745570,56.746864,...,-0.200680,2.897530,47.498103,-6.891934,82.211560,17.788440,21.9,-2.9,29612.0,19877.0
0500000US72151,"Yabucoa Municipio, Puerto Rico",33499,15.803457,26.753037,48.365623,78.862056,0.000000,0.032837,99.919401,18.639362,...,0.031540,-35.826575,53.034419,0.486582,81.920068,18.079932,19.8,-4.4,24078.0,16295.0
0500000US72153,"Yauco Municipio, Puerto Rico",35428,14.663543,27.238343,47.868917,3.799255,0.448798,0.016936,99.364909,75.101615,...,-0.282018,-9.020507,48.755222,-5.331941,82.184244,17.815756,20.2,-3.8,21722.0,14743.0

In [52]:
education=pd.read_csv('./education/education_2019_cleaned.csv')
education.set_index('GEO_ID',inplace=True)
education.drop(axis=1,labels=['Unnamed: 0'],inplace=True)

In [53]:
final_tally['hs_deg']=education['high_school_deg']
final_tally['bac_deg']=education['bachelor_deg']

/tmp/ipykernel_11156/1582709748.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['hs_deg']=education['high_school_deg']
/tmp/ipykernel_11156/1582709748.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_tally['bac_deg']=education['bachelor_deg']

In [79]:
r='REPUBLICAN'
d='DEMOCRAT'
election1=pd.read_csv('./election_results/countypres_2020.csv')
election=election1.loc[(election1['year']==2020) & ((election1['party']==r)|(election1['party']==d))]
election_old=election1.loc[(election1['year']==2016) & ((election1['party']==r)|(election1['party']==d))]
election.dropna(inplace=True)
election_old.dropna(inplace=True)

/tmp/ipykernel_11156/137556527.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  election.dropna(inplace=True)
/tmp/ipykernel_11156/137556527.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  election_old.dropna(inplace=True)

In [80]:
election_old[:5]

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
40517,2016,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,5936,24973,20220315,TOTAL
40518,2016,ALABAMA,AL,AUTAUGA,1001.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,18172,24973,20220315,TOTAL
40520,2016,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,18458,95215,20220315,TOTAL
40521,2016,ALABAMA,AL,BALDWIN,1003.0,US PRESIDENT,DONALD TRUMP,REPUBLICAN,72883,95215,20220315,TOTAL
40523,2016,ALABAMA,AL,BARBOUR,1005.0,US PRESIDENT,HILLARY CLINTON,DEMOCRAT,4871,10469,20220315,TOTAL

In [81]:
election['GEO_ID']=election['county_fips'].apply(lambda x:'0500000US'+str(int(x)).zfill(5))
election_old['GEO_ID']=election_old['county_fips'].apply(lambda x:'0500000US'+str(int(x)).zfill(5))

/tmp/ipykernel_11156/575275784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  election['GEO_ID']=election['county_fips'].apply(lambda x:'0500000US'+str(int(x)).zfill(5))
/tmp/ipykernel_11156/575275784.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  election_old['GEO_ID']=election_old['county_fips'].apply(lambda x:'0500000US'+str(int(x)).zfill(5))

Empty DataFrame
Columns: [year, state, state_po, county_name, county_fips, office, candidate, party, candidatevotes, totalvotes, version, mode, GEO_ID]
Index: []

In [82]:
elections_pc=100*election.groupby(['GEO_ID','party'])['candidatevotes'].sum()/election.groupby(['GEO_ID','party'])['totalvotes'].mean()
elections_old_pc=100*election_old.groupby(['GEO_ID','party'])['candidatevotes'].sum()/election_old.groupby(['GEO_ID','party'])['totalvotes'].mean()

In [85]:
elections_old_pc[:5]

GEO_ID          party
0500000US01001  DEMOCRAT      23.769671
                REPUBLICAN    72.766588
0500000US01003  DEMOCRAT      19.385601
                REPUBLICAN    76.545712
0500000US01005  DEMOCRAT      46.527844
dtype: float64

In [86]:
for x in final_tally.index.intersection(election['GEO_ID']):
    final_tally.loc[x,'democrat']=elections_pc[x][d]
    final_tally.loc[x,'republican']=elections_pc[x][r]
for x in final_tally.index.intersection(election_old['GEO_ID']):
    final_tally.loc[x,'democrat_old']=elections_old_pc[x][d]
    final_tally.loc[x,'republican_old']=elections_old_pc[x][r]

In [87]:
final_tally=final_tally.dropna()

In [88]:
final_tally.to_csv('../aggregate.csv')

In [89]:
final_tally.loc[:,'democrat_old']

GEO_ID
0500000US01001    23.769671
0500000US01003    19.385601
0500000US01005    46.527844
0500000US01007    21.249575
0500000US01009     8.425825
                    ...
0500000US56037    18.861646
0500000US56039    57.923497
0500000US56041    14.191263
0500000US56043    13.948610
0500000US56045     8.479864
Name: democrat_old, Length: 3115, dtype: float64